spring:
  application:
    name: twitchbot
    build-id: @build.id@
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/mariadb
    username: ${DB_USER:mariadb}
    password: ${DB_PASSWORD:mariadb}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,db
server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

twitch:
  api-key: ${API_KEY:default_secret_key}
  upload-api-key: ${UPLOAD_API_KEY:default_upload_secret_key}
  song-upload-path: ${SONG_UPLOAD_PATH:/uploads/songs}
  song-delay-seconds: 5
  redirect-uri-host: ${TWITCH_REDIRECT_URI_HOST:https://music.phat.wtf}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
