apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: twitchbotapp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: music.phat.wtf
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1buffering
        value: |
          maxrequestbodybytes: 104857600
          memrequestbodybytes: 20971520
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.entrypoints
        value: websecure
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.tls
        value: "true"
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - music.phat.wtf
            secretName: music-phat-wtf-tls

configMapGenerator:
  - name: twitchbotapp-config
    behavior: merge
    literals:
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB
