package dev.phatanon.service.chat;

import dev.phatanon.model.ChatMessageContext;
import dev.phatanon.service.TwitchBotService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

@Component
public class MusicCommandHandler implements ChatMessageHandler {

    private final String redirectUriHost;
    private final TwitchBotService twitchBotService;

    public MusicCommandHandler(@Value("${twitch.redirect-uri-host}") String redirectUriHost, @Lazy TwitchBotService twitchBotService) {
        this.redirectUriHost = redirectUriHost;
        this.twitchBotService = twitchBotService;
    }

    @Override
    public boolean canHandle(ChatMessageContext context) {
        return context.getMessage().trim().equalsIgnoreCase("!music");
    }

    @Override
    public void handle(ChatMessageContext context) {
        String response = "All music was generated by AI by the chat members. " + redirectUriHost + "/player.html";
        twitchBotService.sendChatMessage(response);
    }
}
