package dev.phatanon.service.chat;

import dev.phatanon.entity.CustomCommand;
import dev.phatanon.model.ChatMessageContext;
import dev.phatanon.repository.CustomCommandRepository;
import dev.phatanon.service.TwitchBotService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContext;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.*;

class CustomCommandHandlerTest {

    private CustomCommandRepository repository;
    private TwitchBotService twitchBotService;
    private ApplicationContext applicationContext;
    private CustomCommandHandler handler;
    private final String redirectUriHost = "http://test-host";

    @BeforeEach
    void setUp() {
        repository = mock(CustomCommandRepository.class);
        twitchBotService = mock(TwitchBotService.class);
        applicationContext = mock(ApplicationContext.class);
        handler = new CustomCommandHandler(repository, twitchBotService, redirectUriHost, applicationContext);
    }

    @Test
    void testCanHandle() {
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!music"))
                .thenReturn(Optional.of(new CustomCommand("!music", "Response")));
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!MUSIC"))
                .thenReturn(Optional.of(new CustomCommand("!music", "Response")));
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!other"))
                .thenReturn(Optional.empty());

        ChatMessageContext musicContext = ChatMessageContext.builder().message("!music").build();
        ChatMessageContext musicCapsContext = ChatMessageContext.builder().message("!MUSIC").build();
        ChatMessageContext otherContext = ChatMessageContext.builder().message("!other").build();
        ChatMessageContext noBangContext = ChatMessageContext.builder().message("music").build();

        assertTrue(handler.canHandle(musicContext));
        assertTrue(handler.canHandle(musicCapsContext));
        assertFalse(handler.canHandle(otherContext));
        assertFalse(handler.canHandle(noBangContext));
    }

    @Test
    void testHandle() {
        String responseTemplate = "All music was generated by AI by the chat members. ${twitch.redirect-uri-host}/player.html";
        CustomCommand command = new CustomCommand("!music", responseTemplate);
        
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!music"))
                .thenReturn(Optional.of(command));
        
        ChatMessageContext context = ChatMessageContext.builder()
                .message("!music")
                .build();

        handler.handle(context);

        verify(twitchBotService).sendChatMessage("All music was generated by AI by the chat members. http://test-host/player.html");
    }

    @Test
    void testHandleWithArguments() {
        CustomCommand command = new CustomCommand("!test", "Response");
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!test"))
                .thenReturn(Optional.of(command));

        ChatMessageContext context = ChatMessageContext.builder()
                .message("!test arg1 arg2")
                .build();

        handler.handle(context);

        verify(twitchBotService).sendChatMessage("Response");
    }

    @Test
    void testHandleJavaMethod() {
        CustomCommand command = new CustomCommand("!java", "ignored");
        command.setJavaMethodName("testHandler");
        
        when(repository.findByCommandNameIgnoreCaseAndEnabledTrue("!java"))
                .thenReturn(Optional.of(command));
        
        CustomCommandJavaHandler mockHandler = mock(CustomCommandJavaHandler.class);
        when(applicationContext.getBean("testHandler", CustomCommandJavaHandler.class))
                .thenReturn(mockHandler);

        ChatMessageContext context = ChatMessageContext.builder()
                .message("!java arg1 arg2")
                .senderName("testUser")
                .build();

        handler.handle(context);

        verify(mockHandler).handle(eq("testUser"), eq(new String[]{"arg1", "arg2"}));
        verifyNoInteractions(twitchBotService);
    }
}
