CREATE TABLE custom_commands (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    command_name VARCHAR(255) NOT NULL UNIQUE,
    response TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO custom_commands (command_name, response) VALUES ('!music', 'All music was generated by AI by the chat members. ${twitch.redirect-uri-host}/player.html');
